### ISSUE TITLE
A baseline_nob64 test fails?

### ISSUE THREAD

**Issue by matthew-renodin** [corelight/community-id-spec#28]
I reviewed this file and ran a test:

https://github.com/corelight/community-id-spec/blob/master/baseline/baseline_nob64.json

The last two test:
 {"proto": 46, "saddr": "10.1.12.1", "daddr": "10.1.12.2", "sport": null, "dport": null, "communityid": "1:28794b920a095bb89f513c934a0c957e4147ccac"}, 
{"proto": 46, "saddr": "10.1.12.2", "daddr": "10.1.12.1", "sport": null, "dport": null, "communityid": "1:28794b920a095bb89f513c934a0c957e4147ccac"}

The community ID for this appears to be incorrect. I think this community ID came from having the IPs flipped based on my test. When I flip it so 10.1.12.2 comes first and 10.1.12.1 comes second in the byte array it gives me: 28794b920a095bb89f513c934a0c957e4147ccac

I think it should be: 
1f2f15b2c1f825376e9a372350b6e06202e7f1c7

**Comment by ckreibich** [comment]
That's correct, you get `28794b920a095bb89f513c934a0c957e4147ccac` for both, because Community ID assumes these are bidirectional flows — i.e., you _want_ packets from 10.1.12.1 to 10.1.12.2 and from 10.1.12.2 to 10.1.12.1 to be treated as the same flow.

The port-less tuples are a corner case that is unlikely to come up in practice, and there are several Community ID implementations that don't support it at all. Do you have a particular protocol or scenario where you need those to be treated unidirectionally?

**Comment by matthew-renodin** [comment]
I thought the 10.1.12.1 would be first in the buffer, index [2,3,4,5], and 10.1.12.2. would be in index [6,7,8,9]. 

If the source address is 10.1.12.1 167840769, 10.1.12.2 167840770. I only get 28794b920a095bb89f513c934a0c957e4147ccac if I make 10.1.12.2 the first number in the buffer.

**Comment by ckreibich** [comment]
> I thought the 10.1.12.1 would be first in the buffer, index [2,3,4,5], and 10.1.12.2. would be in index [6,7,8,9].

Yes, that's correct. And it's the same regardless of how you order the IP addresses. You can look over the ordering logic here:

https://github.com/corelight/pycommunityid/blob/master/communityid/algo.py#L179-L197
https://github.com/corelight/pycommunityid/blob/master/communityid/algo.py#L205-L216

I just pushed a new `pycommunityid` release to make comparing buffers easier, since it was previously buried in the code and needed futzing with comments. If you install it and run `community-id -vv`, you now see the bytes going into the hash buffer. Maybe this helps you with troubleshooting.

```
$ community-id -vv --no-base64 46 10.1.12.1 10.1.12.2
INFO     CommunityID for 10.1.12.1 -> 10.1.12.2, proto 46, ordered:
INFO     | seed    00:00
INFO     | ipaddr  0a:01:0c:01
INFO     | ipaddr  0a:01:0c:02
INFO     | proto   2e
INFO     | padding 00
1:28794b920a095bb89f513c934a0c957e4147ccac
```
Reversing the IPs makes no difference, since the Community ID algorithm internally orders them so that both directions get considered as the the same flow tuple:

```
$ community-id -vv --no-base64 46 10.1.12.2 10.1.12.1
INFO     CommunityID for 10.1.12.2 -> 10.1.12.1, proto 46, flipped:
INFO     | seed    00:00
INFO     | ipaddr  0a:01:0c:01
INFO     | ipaddr  0a:01:0c:02
INFO     | proto   2e
INFO     | padding 00
1:28794b920a095bb89f513c934a0c957e4147ccac
```
You can see it's the same, but Community ID realizes that the second tuple is flipped, i.e., it's a reverse flow. So it internally sorts it to 10.1.12.1 -> 10.1.12.2 prior to hashing.

**Comment by matthew-renodin** [comment]
I'll trace through this on Monday, but when I examined my buffer the order you show gave me 1f2f15b2c1f825376e9a372350b6e06202e7f1c7

it would look like the following to get 28794b920a095bb89f513c934a0c957e4147ccac. 

INFO     | seed    00:00
INFO     | ipaddr  0a:01:0c:02
INFO     | ipaddr  0a:01:0c:01
INFO     | proto   2e
INFO     | padding 00

I'll follow up with my buffer logs. 

FYI, all other cases work correctly which made me think there was an rule I am missing.

**Comment by ckreibich** [comment]
Cool! We'll get there. :-) I think you're just missing a small bit somewhere in the flip logic. I'm happy to look at your sources to help, if interested.

**Comment by matthew-renodin** [comment]
Here is a link to the code in a project.
https://github.com/matthew-renodin/communityid_typescript_test

**Comment by ckreibich** [comment]
That's great. Whenever your package is ready, feel free to submit an issue to let us know, or submit a PR for https://github.com/corelight/community-id-spec/blob/master/README.md to include a pointer to your work. Thanks!
